services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_EXTRA_DATABASES: ${EXTRA_DBS}
    ports:
      - "${MYSQL_FW_PORT}:3306"
    volumes:
      - ./init-extra-dbs.sh:/docker-entrypoint-initdb.d/init-extra-dbs.sh:ro
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
    ports:
      - "${PHPMYADMIN_FW_PORT}:80"

  web:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "${WEB_FW_PORT}:80"
    volumes:
      - ./public:/usr/share/nginx/html:rw

  ftp:
    image: fauria/vsftpd
    container_name: ftp
    restart: always
    ports:
      - "${FTP_FW_PORT}:21"
      - "30000-30009:30000-30009"
    environment:
      FTP_USER: sencoteam
      FTP_PASS: ${SENCOTEAM_PASSWORD}
      PASV_ENABLE: "YES"
      PASV_MIN_PORT: 30000
      PASV_MAX_PORT: 30009
      PASV_ADDRESS: 0.0.0.0   # 🌍 Abierto a toda la red
      FILE_OPEN_MODE: 0777
      LOCAL_UMASK: 000
      LOG_STDOUT: "true"
    volumes:
      - ./public:/home/vsftpd/sencoteam:rw

volumes:
  mysql_data:
